name: Legacy test

on: 
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
    
    - name: Install ogmios
      uses: milos-ethernal/ogmios-action@13e2be0b00da80f26bb8583fa129bd7c08856a49

    - name: Test
      run: ogmios --version
